model:
  input_channels: 3
  init_dim: 64
  dim: 64
  resnet_block_groups: 8
  dim_mults: [1, 2, 4, 8]
  steps: 20
  loss_function: 'MSELoss' # MSELoss | L1Loss

data:
  dataset: 'pascal_voc'
  augmentations:

    ShiftScaleRotate:
      shift_limit: 0.1
      scale_limit: 0.1
      rotate_limit: 30
      probability: 0.3

    RGBShift:
      r_shift_limit: 25
      g_shift_limit: 25
      b_shift_limit: 25
      probability: 0.5

    RandomBrightnessContrast:
      brightness_limit: 0.3
      contrast_limit: 0.3
      probability: 0.3

  input_size: 128

training:
  epochs: 500
  batch_size: 16
  learning_rate: 0.00001
  device: 'cuda'
  num_workers: 4


